# Generated by Django 3.0.7 on 2020-11-03 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_networks_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='network_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Networks'),
        ),
    ]
