# Generated by Django 3.0.7 on 2020-11-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201103_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='networks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='results',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
